from __future__ import annotations

import argparse
from pathlib import Path

import polars as pl


def prepare(source: Path, output: Path) -> int:
    frame = (
        pl.read_parquet(source, columns=["mal_id", "bangumi_subject_id"])
        .drop_nulls()
        .unique("mal_id", keep="first")
        .sort("mal_id")
    )
    data = ",".join(
        f"{int(mal_id)}:{int(subject_id)}"
        for mal_id, subject_id in frame.iter_rows()
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        "// Generated by scripts/prepare_bangumi_browser_map.py.\n"
        f'const DATA = "{data}";\n\n'
        "export const bangumiSubjectByMal = new Map<number, number>(\n"
        "  DATA.split(\",\").map((pair) => {\n"
        "    const [malId, subjectId] = pair.split(\":\", 2);\n"
        "    return [Number(malId), Number(subjectId)];\n"
        "  }),\n"
        ");\n",
        encoding="utf-8",
    )
    return frame.height


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        type=Path,
        default=Path(
            "data/processed/anime-model-open-2026-27/"
            "bangumi-mapping.parquet"
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("app/lib/bangumi-map.generated.ts"),
    )
    args = parser.parse_args()
    print(prepare(args.source, args.output))


if __name__ == "__main__":
    main()
