"""Build conservative series groups from explicit catalog relation edges."""
import argparse
import json
import re
import unicodedata
from pathlib import Path

import zstandard as zstd


def build(source: Path, output: Path):
    with source.open("rb") as file, zstd.ZstdDecompressor().stream_reader(file) as reader:
        payload = json.load(reader)
    owners, titles, entries = {}, {}, []
    for entry in payload["data"]:
        ids = [int(m.group(1)) for url in entry.get("sources", [])
               if (m := re.search(r"myanimelist\.net/anime/(\d+)", url))]
        if not ids:
            continue
        item = ids[0]
        # A shared leading series name is required in addition to a real edge.
        # This avoids joining separate franchises through crossover specials.
        tokens = re.findall(r"[a-z0-9]+", unicodedata.normalize("NFKC", entry["title"]).casefold())
        while tokens and tokens[0] in {"the", "a", "an", "gekijouban", "movie"}:
            tokens.pop(0)
        titles[item] = tokens[0] if tokens else ""
        entries.append((item, entry))
        for url in entry.get("sources", []):
            owners[url.rstrip("/")] = item
    parent = {item: item for item in titles}

    def find(item):
        while parent[item] != item:
            parent[item] = parent[parent[item]]
            item = parent[item]
        return item

    for item, entry in entries:
        for url in entry.get("relatedAnime", []):
            other = owners.get(url.rstrip("/"))
            if other in titles and titles[item] and titles[item] == titles[other]:
                left, right = find(item), find(other)
                parent[max(left, right)] = min(left, right)
    groups = {}
    for item in parent:
        groups.setdefault(find(item), []).append(item)
    pairs = sorted((item, group) for group, items in groups.items() if len(items) > 1 for item in items)
    output.write_text(
        "// Generated by scripts/prepare_browser_series.py; explicit relations + matching series name.\n"
        f"// Source update: {payload.get('lastUpdate')}.\n"
        f"export const animeSeriesGroups = new Map<number, number>({json.dumps(pairs, separators=(',', ':'))});\n",
        encoding="utf-8",
    )
    print(f"Generated {len(pairs)} entries in {sum(len(v) > 1 for v in groups.values())} series groups")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    build(args.source, args.output)
