from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import polars as pl
import zstandard as zstd


MAL_PATTERN = re.compile(r"myanimelist\.net/anime/(\d+)")
SHORT_FORM_TYPES = {"TV", "ONA"}
SHORT_FORM_MAX_SECONDS = 15 * 60


def mal_ids(entry: dict) -> list[int]:
    return [
        int(match.group(1))
        for source in entry.get("sources", [])
        if (match := MAL_PATTERN.search(source)) is not None
    ]


def short_form_ids(source: Path) -> list[int]:
    with source.open("rb") as compressed:
        with zstd.ZstdDecompressor().stream_reader(compressed) as reader:
            entries = json.load(reader)["data"]
    output: set[int] = set()
    for entry in entries:
        duration = entry.get("duration") or {}
        seconds = duration.get("value") if duration.get("unit") == "SECONDS" else None
        if (
            str(entry.get("type") or "").upper() in SHORT_FORM_TYPES
            and int(entry.get("episodes") or 0) >= 2
            and isinstance(seconds, int)
            and seconds <= SHORT_FORM_MAX_SECONDS
        ):
            output.update(mal_ids(entry))
    return sorted(output)


def bahamut_map(mapping_path: Path) -> list[tuple[int, int]]:
    frame = (
        pl.read_parquet(mapping_path, columns=["mal_id", "gamer_id"])
        .filter(pl.col("mal_id").is_not_null() & pl.col("gamer_id").is_not_null())
        .unique()
    )
    ambiguous_gamer = (
        frame.group_by("gamer_id").len().filter(pl.col("len") > 1).select("gamer_id")
    )
    frame = frame.join(ambiguous_gamer, on="gamer_id", how="anti")
    ambiguous_mal = (
        frame.group_by("mal_id").len().filter(pl.col("len") > 1).select("mal_id")
    )
    return [
        (int(mal_id), int(gamer_id))
        for mal_id, gamer_id in frame.join(
            ambiguous_mal, on="mal_id", how="anti"
        ).sort("mal_id").iter_rows()
    ]


def typescript_set(name: str, values: list[int]) -> str:
    return f"export const {name} = new Set<number>({json.dumps(values)});"


def build(
    source: Path,
    relation_flags_path: Path,
    mapping_path: Path,
    output: Path,
) -> None:
    relation_flags = json.loads(relation_flags_path.read_text(encoding="utf-8"))
    non_primary = relation_flags["non_primary_mal_ids"]
    short_forms = short_form_ids(source)
    bahamut = bahamut_map(mapping_path)
    lines = [
        "// Generated by scripts/prepare_browser_metadata.py. Do not edit manually.",
        typescript_set("nonPrimaryAnimeIds", non_primary),
        typescript_set("shortFormAnimeIds", short_forms),
        (
            "export const bahamutSubjectByMal = new Map<number, number>("
            f"{json.dumps(bahamut)});"
        ),
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"wrote {len(non_primary)} relation flags, {len(short_forms)} short forms, "
        f"and {len(bahamut)} Bahamut mappings to {output}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Build browser-only anime metadata.")
    parser.add_argument("source", type=Path)
    parser.add_argument("relation_flags", type=Path)
    parser.add_argument("mapping", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    build(args.source, args.relation_flags, args.mapping, args.output)


if __name__ == "__main__":
    main()
